project:
  type: book

book:
  title: "Inferencia Bayesiana"
  author: "Luis A. Barboza"
  date: "1/29/2024"
  chapters:
    - index.qmd
    - pensamiento.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

