project:
  type: book
  output-dir: docs

book:
  title: "Inferencia Bayesiana"
  author: "Luis A. Barboza"
  date: "1/29/2024"
  chapters:
    - index.qmd
    - pensamiento.qmd
    - unparametro.qmd
    - variosparametros.qmd
    - computacion_bayes.qmd
    - estimacion_modelos1.qmd
    - estimacion_modelos2.qmd
    - estimacion_modelos3.qmd
    - references.qmd
    
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

